In [8]:
import pandas as pd

In [9]:
opioid_data_to_load = 'FINAL_opioid_data_UNCLEAN.csv'

In [10]:
opioid_data_df = pd.read_csv(opioid_data_to_load)
opioid_data_df.head(5)

,Year,countycode,State,county,population,deaths,cruderate,DispenseRate,PersonalIncome,PerCapitaPersonalIncome,LessThanHS,HSDiplomaOnly,SomeCollege,BachelorOrHigher,PovertyPop,PovertyRate,UnemployedPop,UnemployedRate
0,2020,1001,AL,"Autauga County, AL",56145,Suppressed,Suppressed,98.3,45248.0,58877.0,5839.08,18415.56,16113.62,15776.75,6242.0,11.2,1420.0,5.4
1,2020,1003,AL,"Baldwin County, AL",229287,41,17.90,65.0,51348.0,233140.0,20635.83,62824.64,71537.54,74518.28,20189.0,8.9,6159.0,6.2
2,2020,1005,AL,"Barbour County, AL",24589,Suppressed,Suppressed,22.8,37120.0,25180.0,5975.13,9024.16,6835.74,2753.97,5548.0,25.5,676.0,7.8
3,2020,1007,AL,"Bibb County, AL",22136,Suppressed,Suppressed,24.8,34598.0,22223.0,4316.52,9717.70,5467.59,2634.18,3549.0,17.8,639.0,7.3
4,2020,1009,AL,"Blount County, AL",57879,Suppressed,Suppressed,22.8,38351.0,59081.0,9492.16,20315.53,19447.34,8623.97,7525.0,13.1,1143.0,4.6

In [11]:
opioid_data_df.dtypes

Year                         int64
countycode                   int64
State                       object
county                      object
population                   int64
deaths                      object
cruderate                   object
DispenseRate               float64
PersonalIncome             float64
PerCapitaPersonalIncome    float64
LessThanHS                 float64
HSDiplomaOnly              float64
SomeCollege                float64
BachelorOrHigher           float64
PovertyPop                 float64
PovertyRate                float64
UnemployedPop              float64
UnemployedRate             float64
dtype: object

In [12]:
opioid_data_df.isna().sum()

Year                         0
countycode                   0
State                      550
county                       0
population                   0
deaths                       0
cruderate                    0
DispenseRate               550
PersonalIncome             212
PerCapitaPersonalIncome    212
LessThanHS                  36
HSDiplomaOnly               36
SomeCollege                 36
BachelorOrHigher            36
PovertyPop                   1
PovertyRate                  0
UnemployedPop               20
UnemployedRate              20
dtype: int64

In [13]:
opioid_data_df = opioid_data_df.dropna()

In [14]:
opioid_data_df.isna().sum()

Year                       0
countycode                 0
State                      0
county                     0
population                 0
deaths                     0
cruderate                  0
DispenseRate               0
PersonalIncome             0
PerCapitaPersonalIncome    0
LessThanHS                 0
HSDiplomaOnly              0
SomeCollege                0
BachelorOrHigher           0
PovertyPop                 0
PovertyRate                0
UnemployedPop              0
UnemployedRate             0
dtype: int64

In [15]:
opioid_data_df.count()

Year                       11764
countycode                 11764
State                      11764
county                     11764
population                 11764
deaths                     11764
cruderate                  11764
DispenseRate               11764
PersonalIncome             11764
PerCapitaPersonalIncome    11764
LessThanHS                 11764
HSDiplomaOnly              11764
SomeCollege                11764
BachelorOrHigher           11764
PovertyPop                 11764
PovertyRate                11764
UnemployedPop              11764
UnemployedRate             11764
dtype: int64

In [16]:
opioid_data_df.to_csv('FINAL_opioid_data_NONULL.csv')

In [17]:
opioid_data_df['deaths'].value_counts()['Suppressed']

8708

In [18]:
opioid_data_suppressed_df = opioid_data_df[opioid_data_df.deaths != 'Suppressed']
opioid_data_suppressed_df.head(10)

,Year,countycode,State,county,population,deaths,cruderate,DispenseRate,PersonalIncome,PerCapitaPersonalIncome,LessThanHS,HSDiplomaOnly,SomeCollege,BachelorOrHigher,PovertyPop,PovertyRate,UnemployedPop,UnemployedRate
1,2020,1003,AL,"Baldwin County, AL",229287,41,17.90,65.0,51348.0,233140.0,20635.83,62824.64,71537.54,74518.28,20189.0,8.9,6159.0,6.2
27,2020,1055,AL,"Etowah County, AL",102371,13,12.70,102.8,39795.0,103393.0,14127.20,34601.40,35215.62,18426.78,15650.0,15.6,3505.0,8.5
36,2020,1073,AL,"Jefferson County, AL",655342,227,34.60,139.0,58053.0,673341.0,58980.78,173010.29,195947.26,227403.67,92310.0,14.4,21947.0,6.9
44,2020,1089,AL,"Madison County, AL",379453,68,17.90,87.3,56499.0,389696.0,30356.24,72854.98,108144.11,168097.68,39100.0,10.5,9761.0,5.1
48,2020,1097,AL,"Mobile County, AL",412716,46,11.10,98.0,42837.0,414250.0,49938.64,141148.87,122576.65,98639.12,71398.0,17.6,16931.0,8.7
50,2020,1101,AL,"Montgomery County, AL",224639,19,8.46,86.3,47054.0,228448.0,27630.60,57956.86,64022.12,75029.43,44058.0,20.4,9282.0,8.6
51,2020,1103,AL,"Morgan County, AL",119883,14,11.68,67.9,44204.0,123336.0,18342.10,37403.50,36923.96,27333.32,16995.0,14.4,2966.0,5.0
57,2020,1115,AL,"St. Clair County, AL",90739,17,18.74,63.0,43673.0,91333.0,12703.46,31940.13,29399.44,16786.72,9384.0,10.5,2240.0,5.4
58,2020,1117,AL,"Shelby County, AL",221428,24,10.80,64.6,60598.0,223708.0,14171.39,43842.74,64214.12,99199.74,15227.0,7.0,4986.0,4.2
62,2020,1125,AL,"Tuscaloosa County, AL",210758,23,10.90,86.6,40463.0,227153.0,21918.83,62805.88,61541.34,64491.95,28776.0,14.4,7551.0,7.3

In [19]:
opioid_data_suppressed_df.count()

Year                       3056
countycode                 3056
State                      3056
county                     3056
population                 3056
deaths                     3056
cruderate                  3056
DispenseRate               3056
PersonalIncome             3056
PerCapitaPersonalIncome    3056
LessThanHS                 3056
HSDiplomaOnly              3056
SomeCollege                3056
BachelorOrHigher           3056
PovertyPop                 3056
PovertyRate                3056
UnemployedPop              3056
UnemployedRate             3056
dtype: int64

In [20]:
opioid_data_suppressed_df.to_csv('FINAL_opioid_data_NOSUPPRESSED.csv')